### ISSUE TITLE
[Bug]: enableBetterRecipebookSorting not working

### ISSUE THREAD

**Issue by dulphin127** [someaddons/recipeessentials#10]
### Describe the bug you're experiencing

I want to disable the feature where the crafting recipes automatically sort themselves on most used.
I assume in the config file, this is what "enableBetterRecipebookSorting" relates to...

However setting this to false in the config file does not change the behavior.

### Reproducability

I'm using Forge and the BMC3 modpack.
Edit the config/recipeessentials file:

...
"enableBetterRecipebookSorting": false
...

Restart the entire game and observe no difference in behavior in the crafting recipe book.
(Clicking multiple times on a recipe will still automatically sort it and move it around.)

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19.2

### Modloader version

Forge

### Logs

https://gist.github.com/dulphin127/b8ec3bdc99f9af1b9850d09038b43801

**Comment by someaddons** [comment]
fixed in 3.5
