### ISSUE TITLE
[Bug]: Incompatible with "Not Enough Recipe Book [NERB]"

### ISSUE THREAD

**Issue by eliasjurkeit** [someaddons/recipeessentials#11]
### Describe the bug you're experiencing

I don't know which mod's fault it is, but "Recipe Essentials" (Fabric 1.20.1) and "Not Enough Recipe Book [NERB]" (Fabric 1.20.1) are incompatible when used together. The game doesn't crash, but the recipe book icon is still there, which makes me assume that NERB doesn't work at all.

### Reproducability

Install "Not Enough Recipe Book [NERB]" (Fabric 1.20.1) and "Recipe Essentials" (Fabric 1.20.1)

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Fabric

### Logs

https://gist.github.com/eliasjurkeit/a52f4deda94fdfc5fd5df7ecba49d2b8

**Comment by someaddons** [comment]
Recipe essentials literally has that same functionality, not sure why you would install both? :D
