### ISSUE TITLE
[Bug]: Incompatability with Not Enough Recipe Book [NERB] 

### ISSUE THREAD

**Issue by KiraKayn** [someaddons/recipeessentials#12]
### Describe the bug you're experiencing

I've installed both Recipe Essentials and Not Enough Recipe Book ([NERB] https://www.curseforge.com/minecraft/mc-mods/notenoughrecipebook), and by the name of the other mod, you can already figure out that its supposed to disable the recipe book, delete it entirely, but Recipe Essentials cancels that, I have already reported this to SSKirillSS (the other mod dev) and he said this:
![image](https://github.com/user-attachments/assets/4ad308a1-c56d-4805-b20a-7988f0b9d79f)

### Reproducability

Simply install Recipe Essentials and NERB, run the game and you'll see that the recipe book is not disabled.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

https://gist.github.com/KiraKayn/924eefc45108c1a4f0537cfdd1151aa7

**Comment by KiraKayn** [comment]
P.S. Apperantly Im stupid and this has been reported, sorry about that

**Comment by someaddons** [comment]
Recipe essentials literally has that same functionality, not sure why you would install both? :D

**Comment by KiraKayn** [comment]
Yep, realised that a bit late, sorry.
