### ISSUE TITLE
[Bug]: Incompatibility with Easy Shulker Boxes

### ISSUE THREAD

**Issue by VindSole** [someaddons/recipeessentials#14]
### Describe the bug you're experiencing

The mod Easy Shulker boxes updated and became incompatible with this mod, worlds can't load due to a "data pack corruption" and when clicking create a new world the game crashes. I found that setting "cacheRecipes" to False on the mods config fixes the issues, but it means said optimization is no longer active.

### Reproducability

Have cacheRecipes set to true in the config file.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.21.1

### Modloader version

Fabric

### Logs

https://gist.github.com/VindSole/565fbb2fae2b1888792d1b0c06728197

**Comment by someaddons** [comment]
Fixed in 3.8
