### ISSUE TITLE
[Bug]: recipeessentials mod (recipeessentials), Version: 1.20.1-3.6 seems to crash then put togheter with Tough As Nails (toughasnails), Version: 9.2.0.171

### ISSUE THREAD

**Issue by Beata-Scheisner-Petersen** [someaddons/recipeessentials#15]
### Describe the bug you're experiencing

Just have them in the same modpack to don't be able to open a world or make a new world.

[crash-2024-12-05_16.21.09-client.txt](https://github.com/user-attachments/files/18025669/crash-2024-12-05_16.21.09-client.txt)

[latest.log](https://github.com/user-attachments/files/18025686/latest.log)

### Reproducability

Minecraft did load up, but total crash then trying to enter a world or create a new world.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

https://gist.github.com/soppitopp/5fe243a2d15144bcf5f17246a7462941

**Comment by Beata-Scheisner-Petersen** [comment]
May be that it is a Though as nail addon that cause the crash. Efter removed the addons, and moved back recipeessentials it still worked, But I am not sure..

**Comment by someaddons** [comment]
ye that one is unrelated to recipe essentials, it doesnt change the loading just passes it along
