### ISSUE TITLE
[Bug]: Iron Trapdoors recipe doesn't work with this mod installed

### ISSUE THREAD

**Issue by VeggeieDude** [someaddons/recipeessentials#2]
### Describe the bug you're experiencing

Hello! I installed this mod onto my server last night, and today we were trying to craft iron trapdoors but it wouldn't work. Upon removing the mod it worked again however.

### Reproducability

Try to craft iron trapdoors with this mod installed

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Fabric

### Logs

https://gist.github.com/VeggeieDude/0a4c7fae57cccce20e8e7bfcddce42ac

**Comment by someaddons** [comment]
fixed in 2.3
