### ISSUE TITLE
[Bug]: RecipeEssentials causing Nature's Aura Ritual of the Forest Trees to not grow

### ISSUE THREAD

**Issue by HockeyZman2000** [someaddons/recipeessentials#3]
### Describe the bug you're experiencing

Upon growing a tree as part of the ritual, the tree refuses to grow and throws an error in log.

### Reproducability

Load a world with Nature's Aura and RecipeEssentials, attempt the first ritual of the forest, tree does not grow

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

https://gist.github.com/HockeyZman2000/39f635041feed0a6876d18bb85d2f9ca

**Comment by someaddons** [comment]
fixed in 2.8

**Comment by HockeyZman2000** [comment]
Thanks!
