### ISSUE TITLE
[Bug]: Issue with Alloy Forgery and Recipe Essentials causing resources to just dissapear when trying to use them in a Forge.

### ISSUE THREAD

**Issue by E3VL** [someaddons/recipeessentials#4]
### Describe the bug you're experiencing

When building a Forge (Alloy Forgery mo) and trying to use it, it will just eat the resources you put into it.
I have had multiple players on my server report this issue, one of my moderators did some troubleshooting and found that removing Recipe Essentials fixes the issue.

### Reproducability

Install Alloy Forgery and Recipe Essentials.
Try using a forge for any purpose

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19.2

### Modloader version

Fabric

### Logs

https://gist.github.com/E3VL/0019542baa6cda48bb3294498274408f

**Comment by someaddons** [comment]
works just fine for me, can't reproduce the issue
