### ISSUE TITLE
[Bug]: Exception ticking world

### ISSUE THREAD

**Issue by DonorKrovi** [someaddons/recipeessentials#5]
### Describe the bug you're experiencing

Server crash

### Reproducability

idk

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

https://mclo.gs/NfVjysW

**Comment by BugmanBugman** [comment]
https://gist.github.com/BugmanBugman/ebd0a00639d730c24a7e5c1235af549d

got this too. DO you have alex's caves

**Comment by someaddons** [comment]
fixed in 3.1
