### ISSUE TITLE
[Question]: FastSuite

### ISSUE THREAD

**Issue by KostromDan** [someaddons/recipeessentials#6]
### Describe the bug you're experiencing

Seems like this mod is doing absolutelly same function as FastSuite FastFurnace FastWorkbench https://www.curseforge.com/minecraft/mc-mods/fastsuite
Is this mod better?

### Reproducability

-

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19.2

### Modloader version

Forge

### Logs

-

**Comment by someaddons** [comment]
with recipe essentials you dont need the others, it got some additional neat recipe book things ontop
