### ISSUE TITLE
[Bug]: Recipe book still visible when opening curios inventory (1.19.2/Forge)

### ISSUE THREAD

**Issue by drenough** [someaddons/recipeessentials#7]
### Describe the bug you're experiencing

When you add Curios API (Forge/NeoForge), open your inventory, first screenshot you can see the recipe book is disabled which is good, but when clicking on curios button to open more inv, you can see and open the recipe book, which you can see on other 2 screenshots
![2024-04-14_17 00 01](https://github.com/someaddons/recipeessentials/assets/165467072/49e8108d-79af-4213-b7e8-0f650114bf88)
![2024-04-14_17 00 43](https://github.com/someaddons/recipeessentials/assets/165467072/722967f2-cc5a-448e-9d21-78dc0a352654)
![2024-04-14_17 00 46](https://github.com/someaddons/recipeessentials/assets/165467072/9d640ac6-027f-4c3a-be55-bae2f1cfba2e)

### Reproducability

Just add curios with mods that needs it/could use it, like IC2 Classic on 1.19.2, create new world and open your inventory where you click on curios icon/button to open little menu

MC: 1.19.2
Forge loader: 43.3.0
Recipe Essentials: 1.19.2-3.2
Curios API (Forge/NeoForge): 1.19.2-5.1.6.1

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19.2

### Modloader version

Forge

### Logs

https://gist.github.com/drenough/7d5690a8b04a24494300f63c303a11da

**Comment by drenough** [comment]
And when I open furnace, I can still see the recipe book
![2024-04-15_23 07 30](https://github.com/someaddons/recipeessentials/assets/165467072/fa41c29f-7df2-41e6-bf41-6fcd226e92fd)

**Comment by drenough** [comment]
Same thing happening on 1.20.1 version with latest version of recipe essentials, curious and forge: 47.2.0

**Comment by someaddons** [comment]
fixed
