### ISSUE TITLE
[Bug]: Variant Furnaces incompatibility

### ISSUE THREAD

**Issue by crowmaticOrb** [someaddons/recipeessentials#8]
### Describe the bug you're experiencing

When shift clicking into a furnace from [Variant Furnaces](https://modrinth.com/mod/variant-furnaces) the client will crash, and the server will show an error in console.
[Error from server console](https://pastebin.com/m9EZpJmk), the crash on client says the same error.

### Reproducability

Shift click any item into a furnace from variant furnaces.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Fabric

### Logs

https://gist.github.com/BroBoss64/edaa4bfe4885eac42e6909e32d0c0757

**Comment by someaddons** [comment]
Please report to Variant Furnaces, the recipe type should never be null
