### ISSUE TITLE
[Bug]: Mod causing Inventory GUI to not update textures based on nbt every frame

### ISSUE THREAD

**Issue by MundM2007** [someaddons/recipeessentials#9]
### Describe the bug you're experiencing

- I created new items with Kubejs and made Custom Dynamic Textures with Custom Model Data. If changing the custom model data. The Texture doesn't update with this mod installed. Without it it works without problem
- this also affects https://www.curseforge.com/minecraft/mc-mods/shulkerboxtooltip In this case, the shulker box tooltip isn't updated at all if the shulker box isn't being hold: https://github.com/MisterPeModder/ShulkerBoxTooltip/issues/155

### Reproducability

- add an item or GUI element that changes based texture on nbt. In this case the texture won't update correctly with this mod

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

[latest.log](https://github.com/user-attachments/files/15951737/latest.log)

**Comment by MundM2007** [comment]
@someaddons

**Comment by someaddons** [comment]
disable the "fastItemComparisons" config
